#
# Module manifest for module 'psRadiantOne'
#
# Generated by: Pete Maan
#
# Generated on: 06/09/2026
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'psRadiantOne.psm1'

    # Version number of this module.
    ModuleVersion     = '0.0.1'

    # ID used to uniquely identify this module
    GUID              = 'c7008020-b69c-48ae-9959-974642f61fe4'

    # Author of this module
    Author            = 'Pete Maan'

    # Company or vendor of this module
    CompanyName       = 'PSPETE'

    # Copyright statement for this module
    Copyright         = '(c) Pete Maan. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Enables user interaction with the API for the Radiant Logic RadiantOne platform'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules   = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess    = @( )

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess  = @( )

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules     = @( )

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(

        'Add-R1TruststoreCertificate',
        'Connect-R1Session',
        'Disconnect-R1Session',
        'Export-R1TruststoreCertificate',
        'Get-R1AccessControlSetting',
        'Get-R1AccessToken',
        'Get-R1Aci',
        'Get-R1AciLocation',
        'Get-R1AttributeEncryption',
        'Get-R1AttributeEncryptionKmsSetting',
        'Get-R1DirectoryManager',
        'Get-R1FIDRole',
        'Get-R1FIDUser',
        'Get-R1Session',
        'Get-R1SpecialGroup',
        'Get-R1TruststoreCertificate',
        'New-R1AccessToken',
        'New-R1Aci',
        'New-R1FIDRole',
        'New-R1FIDUser',
        'Remove-R1AccessToken',
        'Remove-R1Aci',
        'Remove-R1FIDRole',
        'Remove-R1FIDUser',
        'Remove-R1TruststoreCertificate',
        'Reset-R1Password',
        'Set-R1AccessControlSetting',
        'Set-R1Aci',
        'Set-R1AttributeEncryption',
        'Set-R1AttributeEncryptionKmsSetting',
        'Set-R1DirectoryManager',
        'Set-R1FIDRole',
        'Set-R1FIDUser',
        'Set-R1FIDUserRole',
        'Set-R1SpecialGroup',
        'Test-R1Aci',
        'Test-R1AdapToken',
        'Test-R1CallerPrivilege',
        'Update-R1AttributeEncryptionKey',
        'Update-R1AuthToken'

    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    # CmdletsToExport   = @()

    # Variables to export from this module
    # VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    # AliasesToExport   = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('RadiantOne', 'Radiant-Logic', 'RadiantLogic', 'REST', 'API', 'Identity', 'LDAP', 'IDDM', 'FID')

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/pspete/psRadiantOne/blob/main/LICENSE.md'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/pspete/psRadiantOne/'

            # A URL to an icon representing this module.
            # IconUri      = 'https://raw.githubusercontent.com/pspete/psRadiantOne/main/docs/media/images/psRadiantOne-Logo-small.png'

            # ReleaseNotes of this module
            ReleaseNotes = 'https://github.com/pspete/psRadiantOne/blob/main/CHANGELOG.md'

        } # End of PSData hashtable

    } # End of PrivateData hashtable

}
